#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Ubuntu
alias u='echo Kaugummi1 | sudo -S apt update -y && sudo apt upgrade -y'
alias please='echo Kaugummi1 | sudo -S $(history -p !!)'
